import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";

const here = new URL("./", import.meta.url);
const appUrl = new URL("app.js", here);
const entryUrl = new URL("customer-entry.html", here);

assert.equal(fs.existsSync(appUrl), true, "app.js must exist");
assert.equal(fs.existsSync(entryUrl), true, "customer-entry.html must exist");

const js = fs.readFileSync(appUrl, "utf8");
const html = fs.readFileSync(entryUrl, "utf8");
const css = fs.readFileSync(new URL("styles.css", here), "utf8");
const relativeLuminance = (hex) => {
  const channels = hex.match(/[A-Fa-f0-9]{2}/g).map((value) => Number.parseInt(value, 16) / 255);
  const linear = channels.map((value) => value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4);
  return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2];
};
const contrastRatio = (foreground, background) => {
  const values = [relativeLuminance(foreground), relativeLuminance(background)].sort((a, b) => b - a);
  return (values[0] + 0.05) / (values[1] + 0.05);
};
const pageNames = ["index", "product", "cart", "customer-entry", "login", "customer-info", "delivery-info", "delivery-consultation", "confirm", "complete"];

for (const pageName of pageNames) {
  const pageUrl = new URL(`${pageName}.html`, here);
  const pageHtml = fs.readFileSync(pageUrl, "utf8");
  assert.match(pageHtml, /<script src="catalog\.js"><\/script>/, `${pageName}.html must load the isolated prototype 08 catalog`);
}
assert.equal(fs.existsSync(new URL("catalog.js", here)), true, "prototype 08 catalog.js must exist");
const catalogContext = {window: {}};
vm.runInNewContext(fs.readFileSync(new URL("catalog.js", here), "utf8"), catalogContext);
assert.equal(catalogContext.window.NANOHANA_CATALOG.categories.length, 53, "all 53 observed categories must remain available");
assert.equal(catalogContext.window.NANOHANA_CATALOG.products.length, 12, "the agricultural processed-food prototype must contain 12 products");
assert.ok(catalogContext.window.NANOHANA_CATALOG.products.every((item) => item.gcCd === "44"), "all default prototype products must belong to agricultural processed foods");
assert.ok(catalogContext.window.NANOHANA_CATALOG.products.every((item) => !item.image.includes("dumy")), "all default products must use real product images");
for (const item of catalogContext.window.NANOHANA_CATALOG.products) {
  assert.equal(fs.existsSync(new URL(item.image, here)), true, `${item.image} must exist locally`);
}

assert.match(js, /nanohana-purchase-flow-v3/);
assert.match(js, /existing-shipping/);
assert.match(js, /existing-delivery/);
assert.match(js, /new-shipping/);
assert.match(js, /一般発送で注文する/);
assert.match(js, /初めて配達をご希望の方/);
assert.doesNotMatch(js, /新しく定期配達を始めたい/);
assert.match(js, /Web会員CDをお持ちの方/);
assert.match(js, /初めてご注文する方/);
assert.match(js, /暗証番号をお忘れの方は、菜の花村へお問い合わせください/);
assert.match(js, /Web会員CDの発行方法は、本番実装前に確認します/);
assert.doesNotMatch(js, /初回注文の確定時にWeb会員CDが発行され/);
assert.doesNotMatch(js, /Web会員登録済み/);
assert.doesNotMatch(js, /Web会員CDを受け取っている方/);
assert.doesNotMatch(js, /一般発送をご利用の方も、定期配達をご利用中の方もこちらです/);
assert.doesNotMatch(js, /Web会員登録は初めて/);
assert.doesNotMatch(js, /住所などを入力し、そのまま購入手続きへ進めます/);
assert.doesNotMatch(js, /配達地域と曜日の確認が必要なため、最初に電話でご相談ください/);
assert.doesNotMatch(js, /配達を利用中で、Web注文は初めて/);
const entryRenderer = js.match(/function renderCustomerEntry\(\) \{([\s\S]*?)\n  \}\n\n  function renderLogin/)[1];
assert.equal((entryRenderer.match(/一般発送で注文する/g) || []).length, 1, "customer entry must not repeat the general-shipping label");
const catalogRenderer = js.match(/function renderCatalog\(\) \{([\s\S]*?)\n  \}\n\n  function renderProductDetail/)[1];
assert.match(catalogRenderer, /class="category-summary"/);
assert.match(catalogRenderer, /カテゴリー変更/);
assert.match(catalogRenderer, /data-result-count/);
assert.doesNotMatch(catalogRenderer, /market-tools/);
assert.doesNotMatch(catalogRenderer, /popular-chips/);
assert.doesNotMatch(catalogRenderer, /selection-bar/);
assert.match(js, /const officialHomeUrl = "https:\/\/www\.nano87\.com\/"/);
assert.match(js, /target="_blank" rel="noopener noreferrer"/);
assert.match(js, /<small>お買い物ページ<\/small>/);
assert.match(js, /get\("gc_cd"\) \|\| "44"/);
assert.match(js, /params\.set\("gc_cd", code\)/);
assert.match(js, /params\.set\("gc_cd", activeCategory\)/);
assert.match(js, /product\.html\?code=/);
assert.match(js, /class="product-image-link"/);
assert.match(js, /class="product-name-link"/);
assert.match(js, /width="600" height="700"/);
assert.match(js, /function productQuantityControl\(item\)/);
assert.match(js, /data-quantity-plus/);
assert.match(js, /data-quantity-minus/);
assert.match(js, /function changeProductQuantity\(code, delta\)/);
assert.match(js, /delete state\.cart\[code\]/);
assert.match(js, /data-quantity-status aria-live="polite"/);
assert.match(js, /data-quantity-status.*textContent/);
assert.match(js, /aria-pressed="true"/);
const quantityHelper = js.match(/function nextProductQuantity\(current, delta\) \{([^}]+)\}/);
assert.ok(quantityHelper, "pure quantity helper must exist");
const quantityContext = {};
vm.runInNewContext(`result = (current, delta) => {${quantityHelper[1]}}`, quantityContext);
assert.equal(quantityContext.result(0, 1), 1, "plus changes zero to one");
assert.equal(quantityContext.result(2, -1), 1, "minus reduces quantity by one");
assert.equal(quantityContext.result(1, -1), 0, "minus changes one to zero so the add button can return");
assert.match(js, /product: renderProductDetail/);
assert.match(css, /\.entry-layout\{grid-template-columns:1fr 1fr;align-items:stretch\}/);
assert.match(css, /\.entry-layout>\.choice-card\.is-primary\{display:grid;grid-template-rows:auto 1fr;justify-content:stretch\}/);
assert.match(css, /\.entry-layout>\.choice-card\.is-primary>\.choice-action\{align-self:center;margin-top:0\}/);
assert.match(css, /\.form-card\{width:100%;max-width:840px;margin-left:auto;margin-right:auto\}/);
assert.match(css, /\.form-card\.narrow\{max-width:640px\}/);
assert.match(css, /\.empty-card\{width:100%;max-width:720px;margin-left:auto;margin-right:auto;text-align:center\}/);
assert.match(css, /\.actions\{grid-template-columns:1fr 1\.35fr;max-width:720px;margin-left:auto;margin-right:auto\}/);
assert.match(css, /\.entry-layout,\.two-column,\.confirm-layout,\.checkout-layout\{width:100%;margin-left:auto;margin-right:auto\}/);
assert.match(css, /body\{overflow-x:hidden\}/);
assert.match(css, /safe-area-inset-bottom/);
assert.match(css, /\.compact-header\{position:fixed/);
assert.match(css, /\.has-compact-header \.compact-header/);
assert.match(js, /data-compact-header aria-hidden="true" inert/);
assert.match(js, /toggleAttribute\("inert", !visible\)/);
assert.match(css, /--content-max:1200px/);
assert.match(css, /\.bottom-nav\{height:calc\(var\(--bottom-nav-height\) \+ env\(safe-area-inset-bottom\)\)/);
assert.match(css, /@media \(min-width:800px\).*\.product-grid\{grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/s);
assert.match(css, /--color-bg:#F8F5EC/);
assert.match(css, /--color-surface:#FFFFFF/);
assert.match(css, /--color-text:#2F352F/);
assert.match(css, /--color-text-muted:#5D655B/);
assert.match(css, /--color-brand:#365B41/);
assert.match(css, /--color-brand-soft:#E7EFE6/);
assert.match(css, /--color-cta:#B85C2C/);
assert.match(css, /--color-accent:#E6C84E/);
assert.match(css, /--color-danger:#A32D2D/);
assert.match(css, /--color-delivery-soft:#E7F4FA/);
assert.match(css, /--color-delivery:#4C92AD/);
assert.match(css, /--radius-card:16px/);
assert.match(css, /--radius-control:12px/);
assert.match(css, /--tap-size:44px/);
assert.match(css, /--card-shadow:/);
assert.ok(contrastRatio("#2F352F", "#F8F5EC") >= 4.5, "main text on page background must meet WCAG AA");
assert.ok(contrastRatio("#5D655B", "#F8F5EC") >= 4.5, "muted text on page background must meet WCAG AA");
assert.ok(contrastRatio("#365B41", "#FFFFFF") >= 4.5, "brand action on white must meet WCAG AA");
assert.ok(contrastRatio("#FFFFFF", "#B85C2C") >= 4.5, "purchase CTA must meet WCAG AA");
const cssOutsideTokenDefinition = css.replace(/^:root\{[^}]+\}\n/, "");
assert.doesNotMatch(cssOutsideTokenDefinition, /#[A-Fa-f0-9]{3,8}\b/, "component rules must use design tokens instead of raw hex colors");
assert.match(css, /\.buy-button[^}]*background:var\(--color-cta\)/);
assert.match(js, />カートに追加<\/button>/);
assert.match(css, /\.add-button[^}]*min-height:var\(--tap-size\)/);
assert.match(css, /\.quantity-stepper button[^}]*width:var\(--tap-size\)/);
assert.match(css, /\.product-card[^}]*border-radius:var\(--radius-card\)/);
assert.match(css, /\.search-form[^}]*border-radius:var\(--radius-pill\)/);
assert.match(css, /\.product-image-wrap\{[^}]*aspect-ratio:6\/7/);
assert.match(css, /\.product-image-wrap img\{[^}]*object-fit:contain/);
assert.match(css, /\.product-detail-image\{[^}]*aspect-ratio:6\/7/);
assert.match(css, /\.product-detail-image img\{[^}]*object-fit:contain/);
assert.match(css, /\.delivery-link\{[^}]*background:var\(--color-delivery-soft\)/);
assert.match(css, /\.product-copy\{[^}]*min-height:0/);
assert.match(css, /\.product-purchase-row\{[^}]*margin-top:8px/);
assert.doesNotMatch(css, /\.product-copy\{[^}]*min-height:190px/);
assert.match(css, /\.purchase-cta[^}]*background:var\(--color-cta\)/);
assert.match(css, /\.product-image-wrap>span[^}]*background:var\(--color-accent\)/);
assert.match(css, /\.qty-controls \.remove[^}]*color:var\(--color-danger\)/);
assert.match(css, /button:disabled[^}]*cursor:not-allowed/);
assert.match(css, /button:focus-visible,a:focus-visible,input:focus-visible[^}]*var\(--color-focus\)/);
assert.match(js, /class="primary-button purchase-cta" href="customer-entry\.html">購入手続きへ進む/);
assert.match(js, /class="primary-button purchase-cta" href="confirm\.html">注文内容の確認へ/);
assert.match(js, /class="primary-button purchase-cta" href="complete\.html">試作の注文完了画面へ/);
assert.doesNotMatch(js, /class="primary-button" href="login\.html">ログインして進む/);
assert.match(js, /class="skip-link" href="#main"/);
assert.match(js, /id="main" tabindex="-1"/);
assert.match(html, /data-page="customer-entry"/);
assert.doesNotMatch(js, /fetch\s*\(/);
assert.doesNotMatch(js, /XMLHttpRequest/);
assert.doesNotMatch(js, /sendBeacon/);
assert.doesNotMatch(js, /nano87\.sakura\.ne\.jp/);

console.log("prototype structure: ok");
